### ISSUE TITLE
Can't merge lora in to model

### ISSUE THREAD

**Issue by CasanovaSan** [hako-mikan/sd-webui-supermerger#269] opened 2023-10-31 22:21 UTC
So i am trying to merge a lora in to my private model but i get this error
```
Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 594, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl, keychanger)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 700, in newpluslora
    bkey = keychanger[outkey].replace("weight","bias")
KeyError: 'transformer_text_model_encoder_layers_0_self_attn_out_proj'
```

![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/138389174/712139ff-412d-45e1-bb3c-809140de294e)

**Comment by hako-mikan** [comment] 2023-11-12 13:56
Tell me your web-ui version, LoRA(Lycoris/Locon) and SD(1.X/2.X.XL) version.

**Comment by CasanovaSan** [comment] 2023-11-13 09:05
> Tell me your web-ui version, LoRA(Lycoris/Locon) and SD(1.X/2.X.XL) version.

![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/138389174/3fe87fa4-f55c-475e-9132-450fe7d3cbb0)
those are the versions of web ui and a1111 also i am using a personal sd 1.5 mix, and the Lora (lycoris) is this one https://civitai.com/models/190863 (mature content, do not open when not alone)

**Comment by hako-mikan** [comment] 2023-11-13 13:42
In my test, https://civitai.com/models/190863 could be merged into checkpoint.
So you should check your model using [model toolkit.](https://github.com/arenasys/stable-diffusion-webui-model-toolkit).

**Comment by CasanovaSan** [comment] 2023-11-13 18:30
> In my test, https://civitai.com/models/190863 could be merged into checkpoint. So you should check your model using [model toolkit.](https://github.com/arenasys/stable-diffusion-webui-model-toolkit).

made a new mix and i managed to merge a lora to the model mix but when i try to merge that lycoris it gives me this error
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/138389174/d73cf8dd-8bec-4bdd-af82-2928a051edfa)

**Comment by hako-mikan** [comment] 2023-11-14 15:56
Can your lycoris be loaded in txt2img tab?

**Comment by Neytiri7** [comment] 2023-11-20 19:43
I also have an error when merging lora, so it doesn't merge.

It's the same condition as CasanovaSan above.

In the past, if you ignored that error and kept trying, it was merged intermittently.

However, not all lora are merged at this time, with the corresponding error occurring.

The corresponding lora operates normally in t2i.

`Traceback (most recent call last):
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run    result = context.run(func, *args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 705, in pluslora
    if orig_checkpoint: sd_models.load_model(checkpoint_info=orig_checkpoint)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_models.py", line 649, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_models.py", line 537, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 273, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\lowvram.py", line 52, in send_me_to_gpu
    module_in_gpu.to(cpu)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!`

**Comment by mating123456** [comment] 2023-11-24 18:19
I was in the same situation

**Comment by pnotisdev** [comment] 2023-11-29 05:16
I have this problem tired uninstalling python, supermerger and stable diffusion

**Comment by gufengduyun** [comment] 2023-11-30 01:55
我也是遇到同样的问题，在融合LoRA到model中时出现【NotImplementedError: Cannot copy out of meta tensor； no data!】

**Comment by mating123456** [comment] 2023-12-01 14:39
> 问题似乎已经解决，但原因尚不清楚。 有报告称，由于内存不足，可能会出现类似的错误。你们就是在这种情况下工作的吗？

When I returned the SD version to 1.52, everything was fine

**Comment by mating123456** [comment] 2023-12-01 14:49
> 此次更新后，是否还会出现该错误？ 如果您正在检查“cuda”选项，请尝试“cpu”。

I have updated to the latest version, whether I select GPU or CPU, his error is shown as RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by hako-mikan** [comment] 2023-12-01 14:56
Did another error occur?
What situation did error occur?

**Comment by mating123456** [comment] 2023-12-01 15:01
> 是否发生了另一个错误？ 什么情况下发生了错误？

I updated the latest version to merge LORA to Checkpoint. NotImplementedError: Cannot copy out of meta tensor; no data! It doesn't matter if I choose GPU or CPU

**Comment by hako-mikan** [comment] 2023-12-01 15:33
Please select the model you want to merge from the model selection in the upper left, load the model, and then try again.

**Comment by mating123456** [comment] 2023-12-01 15:39
> 请从左上角的模型选择中选择要合并的模型，加载模型，然后重试。

I tried, but the error was different, RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by hako-mikan** [comment] 2023-12-01 15:55
Could you please paste the log that starts with 'Plus LoRA Start' from the command prompt? You don't need to write the model name or anything else.

**Comment by mating123456** [comment] 2023-12-01 16:00
Plus LoRA start
Loading XXXX
Traceback (most recent call last):
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 704, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl,isv2, keychanger)
  File "I:\novelai-webui-aki-v3 (2)\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 801, in newpluslora
    theta_0[wkey], theta_0[bkey]= plusweights(theta_0[wkey], module, bias = theta_0[bkey])
  File "I:\novelai-webui-aki-v3 (2)\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 822, in plusweights
    updown = module.calc_updown(weight.to(dtype=torch.float))
  File "I:\novelai-webui-aki-v3 (2)\extensions-builtin\Lora\network_lora.py", line 76, in calc_updown
    updown = lyco_helpers.rebuild_conventional(up, down, output_shape, self.network.dyn_dim)
  File "I:\novelai-webui-aki-v3 (2)\extensions-builtin\Lora\lyco_helpers.py", line 15, in rebuild_conventional
    return (up @ down).reshape(shape)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
Plus LoRA start
Loading XXX
[Exited, code -1073741819 (0xC0000005)]

**Comment by mating123456** [comment] 2023-12-01 16:20
> 您使用的是旧版本吗？ `\pluslora.py", line 822, in plusweights `是旧版本的代码。

After you updated, I uninstalled it and downloaded it again, using this link https://github.com/hako-mikan/sd-webui-supermerger.git, it is technically a new version, what happened

**Comment by mating123456** [comment] 2023-12-01 16:34
> 您使用的是旧版本吗？ `\pluslora.py", line 822, in plusweights `是旧版本的代码。

Just received the latest version, updated, the error is the same,    
Plus LoRA start
Loading 0.8(0.6(0.7(henmixReal_v22) + 0.3(beautifulRealistic_v40-fp16-no-ema)) + 0.4(598787.fp16)) + 0.2(dalcefov4-fp16-no-ema).safetensors
Loading weights [None] from I:\novelai-webui-aki-v3 (2)\models\Stable-diffusion\0.8(0.6(0.7(henmixReal_v22) + 0.3(beautifulRealistic_v40-fp16-no-ema)) + 0.4(598787.fp16)) + 0.2(dalcefov4-fp16-no-ema).safetensors
Creating model from config: I:\novelai-webui-aki-v3 (2)\configs\v1-inference.yaml
Loading VAE weights specified in settings: I:\novelai-webui-aki-v3 (2)\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Traceback (most recent call last):
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 703, in pluslora
    sd_models.load_model(checkpoint_info=checkpoint_info)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_models.py", line 712, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_models.py", line 600, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_hijack_clip.py", line 273, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1557, in _call_impl
    args_result = hook(self, args)
  File "I:\novelai-webui-aki-v3 (2)\modules\lowvram.py", line 52, in send_me_to_gpu
    module_in_gpu.to(cpu)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by hako-mikan** [comment] 2023-12-01 16:38
Are you using [https://github.com/djstla/novelai-webui-aki-v3](https://github.com/djstla/novelai-webui-aki-v3)?

**Comment by mating123456** [comment] 2023-12-01 16:41
> 您使用的是https://github.com/djstla/novelai-webui-aki-v3吗？

YES

**Comment by mating123456** [comment] 2023-12-01 17:06
> 当查看您的日志时，似乎各种文件更新进展不顺利。在您的日志中， 的位置`sd_models.load_model(checkpoint_info=checkpoint_info)`是 at `line 703`，但实际上应该是 at ` line 725`。 [https://github.com/hako-m​​ikan/](https://github.com/hako-mikan/sd-webui-supermerger/blob/main/scripts/mergers/pluslora.py) sd-webui-supermerger/blob/main/scripts/mergers/pluslora.py 另外，请检查Web-ui的版本。

I tried it again. It's 725
Plus LoRA start
Loading xxx
Loading weights [None] from xxx
Creating model from config: I:\novelai-webui-aki-v3 (2)\configs\v1-inference.yaml
Loading VAE weights specified in settings: I:\novelai-webui-aki-v3 (2)\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Traceback (most recent call last):
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 725, in pluslora
    sd_models.load_model(checkpoint_info=checkpoint_info)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_models.py", line 649, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_models.py", line 537, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_hijack_clip.py", line 273, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "I:\novelai-webui-aki-v3 (2)\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1557, in _call_impl
    args_result = hook(self, args)
  File "I:\novelai-webui-aki-v3 (2)\modules\lowvram.py", line 52, in send_me_to_gpu
    module_in_gpu.to(cpu)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "I:\novelai-webui-aki-v3 (2)\py310\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

The other version is  version: [v1.6.0-2-g4afaaf8a0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)  •  python: 3.10.8  •  torch: 2.1.0+cu121  •  xformers: 0.0.22.post7  •  gradio: 3.41.2  •  checkpoint:

**Comment by mating123456** [comment] 2023-12-01 17:09
> 当查看您的日志时，似乎各种文件更新进展不顺利。在您的日志中，位置`sd_models.load_model(checkpoint_info=checkpoint_info)`是在`line 703`，但实际上应该是在` line 725`。 [https://github.com/hako-m​​​​ikan/](https://github.com/hako-mikan/sd-webui-supermerger/blob/main/scripts/mergers/pluslora.py) sd -webui-supermerger/blob/main/scripts/mergers/pluslora.py 另外，请检查Web-ui的版本。

When I returned to 1.52, everything was fine, I don't know if it was a version compatibility issue

**Comment by mating123456** [comment] 2023-12-02 05:54
> --disable-model-loading-ram-optimization



> 我终于找到原因了。 可能是Web-UI的问题。AUTOMATIC1111 [/stable-diffusion-webui#13087](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13087) 使用`--disable-model-loading-ram-optimization`选项。

I tried to add --disable-model-loading-ram-optimization to the boot option, but there was still an error when merging, the problem still exists

**Comment by hako-mikan** [comment] 2023-12-02 05:56
Are you using XL model?

**Comment by mating123456** [comment] 2023-12-02 05:58
> 您使用的是 XL 型号吗？

IS SD 1.5

**Comment by hako-mikan** [comment] 2023-12-02 06:04
Are there another start up options?

**Comment by mating123456** [comment] 2023-12-02 06:05
In addition  --medvram --xformers --api --autolaunch --no-hashing

**Comment by hako-mikan** [comment] 2023-12-02 07:20
It seems that the issue is due to changes in the memory-related mechanisms when it changed from 1.5 to 1.6. I believe it is fixed now.

**Comment by mating123456** [comment] 2023-12-02 09:12
> 看来该问题是从 1.5 更改为 1.6 时内存相关机制的变化所致。我相信现在已经解决了。

The previous mistakes have disappeared

**Comment by hako-mikan** [comment] 2023-12-02 10:46
With same setting with you, I couldn't reproduce error.
After update, try with "cuda" option.

**Comment by mating123456** [comment] 2023-12-02 15:43
> With same setting with you, I couldn't reproduce error. After update, try with "cuda" option.

Thank you very much for your patience, the problem has been solved, LORA can integrate normally

**Closed** 2023-12-03 00:22 UTC
