### ISSUE TITLE
After restart the saved .safesansor return weird pattern

### ISSUE THREAD

**Issue by DavideAlidosi** [hako-mikan/sd-webui-supermerger#270] opened 2023-11-01 16:07 UTC
Regularly after saving the .safesensor of my pattern merging project and restarting A1111, whatever the prompt the result is always a strange pattern of homogeneous colors.
I have tried various ways with various configurations, but nothing has worked.
Thank's as usually for the support.

**Comment by hako-mikan** [comment] 2023-11-12 13:55
It's difficult to pinpoint the cause based solely on those symptoms, but if you are using LoRA, it's possible that the issue has been addressed in this update.This fixes a bug on the Web-UI side when starting up SuperMerger.

**Comment by DavideAlidosi** [comment] 2023-11-16 09:04
Thanks a lot for the support, now looks like it work as expected.

**Closed** 2023-11-16 09:17 UTC
