### ISSUE TITLE
Can't extract LoRA from ckpt or safetensors

### ISSUE THREAD

**Issue by jockisen** [hako-mikan/sd-webui-supermerger#34] opened 2023-03-21 10:43 UTC
I am trying to extract a LoRA from a model I have both as ckpt and safetensors. Neither work. I have tried many different dimensions, set with and without same to Strength and then pressed Make LoRA. Doesn't work. To be clear: I am only loading in one model to extract from.

The error I get:

```make LoRA start
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 140, in makelora
    if saveto =="" : saveto = makeloraname(model_a,model_b)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 930, in makeloraname
    return "lora_"+model_a+"-"+model_b
TypeError: can only concatenate str (not "NoneType") to str```

**Comment by hako-mikan** [comment] 2023-03-21 17:06
Thanks reporting. Can you tell us about the operating system you use?

**Comment by jockisen** [comment] 2023-03-21 17:15
> Thanks reporting. Can you tell us about the operating system you use?

Windows 10.

**Comment by hako-mikan** [comment] 2023-03-22 16:00
It seems to be a problem related to the file path, so you may be able to solve it by specifying the file name. Try typing something in filename(option).

**Comment by Omenizer** [comment] 2023-03-28 09:20
Same here, tried everything :(

**Comment by Omenizer** [comment] 2023-03-30 08:13
Would be great if this could be fixed! Many thanks in advance - extemely practical extension 🙏🏼

**Comment by hako-mikan** [comment] 2023-03-31 16:22
I'm thinking about it, but I don't understand why. This script was developed by kohya and made available for web-ui. Have you tried kohya's script?
https://github.com/kohya-ss/sd-scripts/blob/main/networks/extract_lora_from_models.py

**Comment by Omenizer** [comment] 2023-03-31 21:57
> I'm thinking about it, but I don't understand why. This script was developed by kohya and made available for web-ui. Have you tried kohya's script? https://github.com/kohya-ss/sd-scripts/blob/main/networks/extract_lora_from_models.py

I haven't - I have all my checkpoints on colab/drive, and downloading would be very hard/slow...

**Comment by hako-mikan** [comment] 2023-04-04 16:08
Kohya's script used in this script is updated. This may improve the result.

U-Net: 320 modules is unusual.
Did you use special model?

**Comment by hako-mikan** [comment] 2023-04-05 03:31
I finally understood the situation. I see that some dreambooths can store LoRA data separately in the model without merging.
The script allows us to create a new LoRA from the differences in the model, but does not support separating LoRAs that have been built into the model by dreambooth. I have never heard of such a feature before. I suggest you ask the author of dreambooth how to separate them. It will take time for me to create a new separation tool from now on.

**Comment by Omenizer** [comment] 2023-04-07 06:52
No, I have successfully extracted Loras from my Dreambooth models with Supermerger before! Now I just want to extract Loras from merged or finetuned models - which also used to work, but it stopped working a while ago.

No way you can fix this? Like I said, it used to work just fine...

**Comment by hako-mikan** [comment] 2023-04-07 09:00
Can I download the model same type as you use?
Your model is something to special so I cannot test in my environment.

**Comment by hako-mikan** [comment] 2023-04-07 09:56
Is the model that worked correctly the same model that did not work correctly?

**Comment by Omenizer** [comment] 2023-04-07 10:11
> Is the model that worked correctly the same model that did not work correctly?

No, it's *any* model. Try to make a Lora by doing a-b with Dreamlikeart and SD1.5, or any other combination - you'll get this error

**Comment by Omenizer** [comment] 2023-04-07 10:11
> > Is the model that worked correctly the same model that did not work correctly?
> 
> No, it's _any_ model. Try to make a Lora by doing a-b with Dreamlikeart and SD1.5, or any other combination - you'll get this error

Any model you have minus SD1.5 basically

**Comment by Omenizer** [comment] 2023-04-07 10:30
I don't know how to make this more clear, but before the bug appeared, ANY 2 models would work, and now, NO combination of models or settings works.

**Comment by hako-mikan** [comment] 2023-04-07 10:31
Does this error occurs when A = sd1.5, and B = sd1.5?

**Comment by Omenizer** [comment] 2023-04-07 11:36
Can't try right now, but I'm pretty sure it will happen

**Comment by hako-mikan** [comment] 2023-04-07 14:25
You could success to make lora using old version of this script.
You can downlaod old version from here
https://github.com/hako-mikan/sd-webui-supermerger/tree/ver3

**Comment by Omenizer** [comment] 2023-04-07 14:55
Can I install this on colab somehow?

**Comment by hako-mikan** [comment] 2023-04-07 15:42
Ok. I dont know colab.
So, I updated this script, you can use old lora script in Lora-old tab in latest version.

**Comment by Omenizer** [comment] 2023-04-07 17:41
Thank you for the update! I tried Lora-old and - even with SD15-SD15 - I'm getting a different error: 

make LoRA start
loading SD model : /content/gdrive/MyDrive/SDData/SD15.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 320 modules.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora_old.py", line 171, in makelora
    svd(fullpathfromname(model_a),fullpathfromname(model_b),False,dim,"float",saveto,alpha,beta)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora_old.py", line 395, in svd
    lora_network_o = create_network(1.0, dim, dim, None, text_encoder_o, unet_o)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora_old.py", line 538, in create_network
    network = LoRANetwork(text_encoder, unet, multiplier=multiplier, lora_dim=network_dim, alpha=network_alpha)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora_old.py", line 578, in __init__
    assert lora.lora_name not in names, f"duplicated lora name: {lora.lora_name}"
AssertionError: duplicated lora name: lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q

**Comment by Omenizer** [comment] 2023-04-07 17:41
Did it work for you?

**Comment by hako-mikan** [comment] 2023-04-07 23:45
Yes, it works.
```
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
Text encoder is same. Extract U-Net only.
calculating by svd
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 192/192 [00:48<00:00,  3.98it/s]
enable LoRA for U-Net
LoRA has 576 weights.
Loading extracted LoRA weights: <All keys matched successfully>
LoRA weights are saved to:
```
difference is `create LoRA for U-Net: 192 modules.`
In your case an extra module is being generated. I do not know the cause of this.

**Comment by Omenizer** [comment] 2023-04-08 05:51
What did you do? Sd15-Sd15, default settings?

**Comment by hako-mikan** [comment] 2023-04-08 10:01
Yes, default settings.
Maybe, versions of some modules such as diffusers is not    different.
 https://github.com/hako-mikan/sd-webui-supermerger/issues/38#issuecomment-1493688041

**Comment by yamasoo** [comment] 2023-04-09 04:12
not work both old and new version



make LoRA start
loading SD model : I:\sd2.0-webui\models\Stable-diffusion\V1.5\v1-5-pruned.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading SD model : I:\sd2.0-webui\models\Stable-diffusion\Unstableinkdream\UnstableinkdreamV7.5-photoreal-fp16-no-ema.safetensors
loading u-net: <All keys matched successfully>
Traceback (most recent call last):
  File "I:\sd2.0-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\sd2.0-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "I:\sd2.0-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\sd2.0-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\sd2.0-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\sd2.0-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\sd2.0-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora_old.py", line 171, in makelora
    svd(fullpathfromname(model_a),fullpathfromname(model_b),False,dim,"float",saveto,alpha,beta)
  File "I:\sd2.0-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora_old.py", line 392, in svd
    text_encoder_t, _, unet_t = load_models_from_stable_diffusion_checkpoint(v2, model_a)
  File "I:\sd2.0-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util_old.py", line 735, in load_models_from_stable_diffusion_checkpoint
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)
  File "I:\sd2.0-webui\extensions\sd-webui-supermerger\scripts\mergers\model_util_old.py", line 395, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'

**Comment by Omenizer** [comment] 2023-04-09 11:54
> Yes, default settings. Maybe, versions of some modules such as diffusers is different. [#38 (comment)](https://github.com/hako-mikan/sd-webui-supermerger/issues/38#issuecomment-1493688041)

Thank you for looking into it, unfortunately, even after a fresh install it's not working for me :(

**Comment by hako-mikan** [comment] 2023-04-09 12:10
What version of diffusers?
In my environment, version of diffusers is 0.10.2.
In this version, works correctly.

**Comment by Omenizer** [comment] 2023-04-09 12:13
> What version of diffusers? In my environment, version of diffusers is 0.10.2. In this version, works correctly.

Phew, I don't even know how to check that on colab! I'll try to find out

**Comment by hako-mikan** [comment] 2023-04-13 11:11
Since there are many people reporting this issue, I decided to discuss it elsewhere.
Discuss the rest here.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52

**Closed by hako-mikan** 2023-04-13 11:11 UTC
